### PR TITLE
[sdk-181] [Unity] SDK causes a crash when the requests queue is emptied in "OnApplicationQuit"

### PR DESCRIPTION
**Pull request by ZahidZafar**

### CODE REVIEW

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
These changes don't solve the issue. They just remove the reporting.

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
None of the added logs act like they should according to the spec

**Comment by ZahidZafar** [comment]
> None of the added logs act like they should according to the spec

i.e [Error] Countly issue bla bla

**Comment by ZahidZafar** [comment]
Do we need to add enableConsoleLogging check as well?

**Comment by ArtursKadikis** [comment]
I suggest you read the logging section:
https://support.count.ly/hc/en-us/articles/360037753291-SDK-development-guide#logging-debug-mode

**Comment by ZahidZafar** [comment]
Debug.LogError("[Countly] Couldn't complete db operation, [" + ex.Message + "]");

**Comment by ArtursKadikis** [comment]
better but the 2 other things you probably didn't do are:
* unique log messages
* logging mode check

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
Try/catch check is not added in all places that access the database

**Comment by ZahidZafar** [comment]
UnityDBCS : MonoBehaviour
in this script db being access, it's just an extra class

**Comment by ZahidZafar** [comment]
Should i delete UnityDBCS?

**Comment by ZahidZafar** [comment]
it's a sample script in the Iboxdb library.

**Comment by ArtursKadikis** [comment]
yeah, delete it, it's not needed

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
Around every function that accesses "AutoBox auto" there should be a try catch block.
You have missed it in "SegmentDao"

**Review by ArtursKadikis — APPROVED** [review]

**Pull request merged**
