### PR TITLE
[Sdk 335] Exit, Bounce, Start removal and More

### PR DESCRIPTION
**Pull request by ZahidZafar**

### CODE REVIEW

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
"start" segmentation should not be removed

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
When closing a view, no "visit" or "start" segmentation should be added.
When changing device ID without merging, the "_isFirstView" should be reset. Add a test that checks this scenario.

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
Missed requested changes:
"When changing device ID without merging, the "_isFirstView" should be reset. **Add a test that checks this scenario.**"

**Comment by ZahidZafar** [comment]
> Missed requested changes:
> "When changing device ID without merging, the "_isFirstView" should be reset. **Add a test that checks this scenario.**"

You are right, I want to make it part of device unit tests,

**Review by ArtursKadikis — APPROVED** [review]

**Pull request merged**
