### PR TITLE
UnityWebRequestHelper added

### PR DESCRIPTION
**Pull request by AliRKat**

### CODE REVIEW

**Comment by AliRKat** [comment]
[[Unity] IEnumerator Get / Post functions](https://trello.com/c/4PLN9YYh/1362-unity-ienumerator-get-post-functions)

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
ifdef around processing the request

no checking if the request succeded

do code reuse

slim it down and pass a monobehaviour 

post/get check should be a common operation

**Comment by AliRKat** [comment]
[[Unity] IEnumerator Get / Post functions](https://trello.com/c/4PLN9YYh/1362-unity-ienumerator-get-post-functions)

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
request -> request url

the whole response handling needs to be reworked

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
add a propper "success" check

**Pull request merged**
