### PR TITLE
Fixed some typos and updated scene

### PR DESCRIPTION
**Pull request by AliRKat**

### CODE REVIEW

**Comment by AliRKat** [comment]
[[Unity] Fix the Typos in the Example App](https://trello.com/c/KdRZQ5sx/1547-unity-fix-the-typos-in-the-example-app)

**Comment by AliRKat** [comment]
[[Unity] Fix the Typos in the Example App](https://trello.com/c/KdRZQ5sx/1547-unity-fix-the-typos-in-the-example-app)

**Review by turtledreams — APPROVED** [review]
I assume all cool and only cosmetic. can you share a before and after pics

**Review by ijunaid — APPROVED** [review]
I assumed that you have already run and test the app with these changes :)

**Pull request merged**
